---
- name: Deploy Database
  hosts: database
  become: yes
  tags: database
  vars_files:
    - versions.yml

  roles:
    - database

- name: Deploy Backend
  hosts: backend
  become: yes
  tags: backend
  vars_files:
    - versions.yml

  roles:
    - backend

- name: Deploy Frontend
  hosts: frontend
  become: yes
  tags: frontend
  vars_files:
    - versions.yml

  roles:
    - frontend

- name: Deploy Monitoring
  hosts: all
  become: yes
  tags: monitoring
  roles:
    - monitoring