---
- name: Rollback Backend
  hosts: backend
  become: yes

  tasks:
    - name: Stop current backend container
      shell: docker stop backend || true

    - name: Remove current backend container
      shell: docker rm backend || true

    - name: Run backup backend version
      shell: |
        docker run -d \
        --name backend \
        --network app-network \
        -p 5234:8000 \
        -e DATABASE_URL=postgresql://postgres:admin@database:5432/boavizta \
        rougha/backend_grp2:backup

- name: Rollback Frontend
  hosts: frontend
  become: yes

  tasks:
    - name: Stop current frontend container
      shell: docker stop frontend || true

    - name: Remove current frontend container
      shell: docker rm frontend || true

    - name: Run backup frontend version
      shell: |
        docker run -d \
        --name frontend \
        -p 4201:80 \
        rougha/frontend_grp2:backup