---
- name: Pull backend image
  docker_image:
    name: "rougha/backend_grp2:{{ backend_version }}"
    source: pull

- name: Backup old backend image
  shell: |
    docker tag rougha/backend_grp2:1.0 rougha/backend_grp2:backup || true

- name: Stop old backend container
  shell: docker stop backend || true

- name: Remove old backend container
  shell: docker rm backend || true

- name: Create Docker network
  shell: docker network create app-network || true

- name: Wait for database to be ready
  shell: |
    until docker exec database pg_isready -U postgres; do
      echo "Waiting for database..."
      sleep 2
    done
  register: db_ready
  retries: 15
  delay: 2
  until: db_ready.rc == 0

- name: Start new backend container
  shell: |
    docker run -d \
    --name backend \
    --network app-network \
    -p 5234:8000 \
    -e DATABASE_URL=postgresql://postgres:admin@database:5432/boavizta \
    rougha/backend_grp2:{{ backend_version }}

- name: Wait for backend
  pause:
    seconds: 60

- name: Healthcheck backend
  uri:
    url: http://{{ ansible_host }}:5234/docs
    status_code: 200
  register: backend_health
  ignore_errors: yes

- name: Rollback if backend failed
  shell: |
    docker stop backend
    docker rm backend
    docker run -d --name backend -p 5234:8000 rougha/backend_grp2:backup
  when: backend_health.failed